fn main() {
    println!("cargo:rerun-if-changed=src/csharp.rs");
    println!("cargo:rerun-if-changed=go/w2v_bert_uk.go");
    println!("cargo:rerun-if-changed=src/java.rs");
    println!("cargo:rerun-if-changed=src/swift.rs");

    if std::env::var_os("CARGO_FEATURE_C").is_some()
        || std::env::var_os("CARGO_FEATURE_CPP").is_some()
        || std::env::var_os("CARGO_FEATURE_GO").is_some()
    {
        std::fs::create_dir_all("c").expect("failed to create c bindings directory");
        std::fs::create_dir_all("cpp").expect("failed to create C++ bindings directory");

        let crate_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set");
        let c_header = cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::C)
            .with_include_guard("W2V_BERT_UK_H")
            .with_autogen_warning("/* Generated by cbindgen. Do not edit manually. */")
            .generate()
            .expect("failed to generate C bindings");
        c_header.write_to_file("c/w2v_bert_uk.h");

        let cpp_header = cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_language(cbindgen::Language::Cxx)
            .with_include_guard("W2V_BERT_UK_HPP")
            .with_namespace("w2v_bert_uk")
            .with_autogen_warning("/* Generated by cbindgen. Do not edit manually. */")
            .generate()
            .expect("failed to generate C++ bindings");
        cpp_header.write_to_file("cpp/w2v_bert_uk.hpp");
    }

    if std::env::var_os("CARGO_FEATURE_CSHARP").is_some() {
        csbindgen::Builder::default()
            .input_extern_file("src/csharp.rs")
            .csharp_dll_name("w2v_bert_uk")
            .csharp_namespace("W2vBertUk.Native")
            .csharp_class_name("NativeMethods")
            .csharp_class_accessibility("public")
            .generate_csharp_file("csharp/NativeMethods.g.cs")
            .expect("failed to generate C# bindings");
    }

    if std::env::var_os("CARGO_FEATURE_NODEJS").is_some() {
        napi_build::setup();
    }

    if std::env::var_os("CARGO_FEATURE_PYTHON").is_some() {
        pyo3_build_config::add_extension_module_link_args();
    }

    if std::env::var_os("CARGO_FEATURE_SWIFT").is_some() {
        swift_bridge_build::parse_bridges(vec!["src/swift.rs"])
            .write_all_concatenated("swift/generated", env!("CARGO_PKG_NAME"));
    }
}
