#ifndef RUST_ASR_H
#define RUST_ASR_H

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define RUST_ASR_OK 0

#define RUST_ASR_ERROR -1

typedef struct RustAsrOptions {
  const char *model;
  const char *tokenizer;
  const char *lm;
  const char *ort_dylib_path;
  const char *ort_optimization;
  const char *w2v_model_source;
  const char *const *hot_words;
  uint32_t beam_width;
  float lm_weight;
  float word_bonus;
  uintptr_t hot_words_len;
  float hot_word_bonus;
  uint32_t fallback_sample_rate;
  uint32_t w2v_sample_rate;
  uint32_t w2v_feature_size;
  uint32_t w2v_stride;
  uint32_t w2v_feature_dim;
  float w2v_padding_value;
  uint32_t blank_id;
  uint32_t n_best;
  int32_t log_language_model;
  int32_t log_accelerator;
  int32_t skip_decode_errors;
  int32_t normalize_spaces;
  int32_t drop_empty_candidates;
  int32_t lm_bos;
  int32_t lm_eos;
} RustAsrOptions;

typedef struct RustAsrTranscriber {
  uint8_t _private[0];
} RustAsrTranscriber;

struct RustAsrOptions rust_asr_options_default(void);

int32_t rust_asr_initialize_ort(const char *ort_dylib_path, bool *initialized);

int32_t rust_asr_preload_cuda_dylibs(const char *cuda_lib_dir, const char *cudnn_lib_dir);

int32_t rust_asr_transcribe_file(const char *audio_file,
                                    const struct RustAsrOptions *options,
                                    char **transcript);

int32_t rust_asr_transcribe_bytes(const unsigned char *audio_bytes,
                                     uintptr_t audio_bytes_len,
                                     const char *format_hint,
                                     const struct RustAsrOptions *options,
                                     char **transcript);

int32_t rust_asr_transcriber_new(const struct RustAsrOptions *options,
                                    struct RustAsrTranscriber **transcriber);

void rust_asr_transcriber_free(struct RustAsrTranscriber *transcriber);

int32_t rust_asr_transcriber_transcribe_file(struct RustAsrTranscriber *transcriber,
                                                const char *audio_file,
                                                char **transcript);

int32_t rust_asr_transcriber_transcribe_bytes(struct RustAsrTranscriber *transcriber,
                                                 const unsigned char *audio_bytes,
                                                 uintptr_t audio_bytes_len,
                                                 const char *format_hint,
                                                 char **transcript);

char *rust_asr_last_error_message(void);

void rust_asr_string_free(char *value);

#endif  /* RUST_ASR_H */
