#ifndef RUST_ASR_HPP
#define RUST_ASR_HPP

/* Generated by cbindgen. Do not edit manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace rust_asr {

constexpr static const int32_t RUST_ASR_OK = 0;

constexpr static const int32_t RUST_ASR_ERROR = -1;

struct RustAsrOptions {
  const char *model;
  const char *tokenizer;
  const char *lm;
  const char *ort_dylib_path;
  const char *ort_optimization;
  const char *w2v_model_source;
  const char *const *hot_words;
  uint32_t beam_width;
  float lm_weight;
  float word_bonus;
  uintptr_t hot_words_len;
  float hot_word_bonus;
  uint32_t fallback_sample_rate;
  uint32_t w2v_sample_rate;
  uint32_t w2v_feature_size;
  uint32_t w2v_stride;
  uint32_t w2v_feature_dim;
  float w2v_padding_value;
  uint32_t blank_id;
  uint32_t n_best;
  int32_t log_language_model;
  int32_t log_accelerator;
  int32_t skip_decode_errors;
  int32_t normalize_spaces;
  int32_t drop_empty_candidates;
  int32_t lm_bos;
  int32_t lm_eos;
};

struct RustAsrTranscriber {
  uint8_t _private[0];
};

extern "C" {

RustAsrOptions rust_asr_options_default();

int32_t rust_asr_initialize_ort(const char *ort_dylib_path, bool *initialized);

int32_t rust_asr_preload_cuda_dylibs(const char *cuda_lib_dir, const char *cudnn_lib_dir);

int32_t rust_asr_transcribe_file(const char *audio_file,
                                    const RustAsrOptions *options,
                                    char **transcript);

int32_t rust_asr_transcribe_bytes(const unsigned char *audio_bytes,
                                     uintptr_t audio_bytes_len,
                                     const char *format_hint,
                                     const RustAsrOptions *options,
                                     char **transcript);

int32_t rust_asr_transcriber_new(const RustAsrOptions *options,
                                    RustAsrTranscriber **transcriber);

void rust_asr_transcriber_free(RustAsrTranscriber *transcriber);

int32_t rust_asr_transcriber_transcribe_file(RustAsrTranscriber *transcriber,
                                                const char *audio_file,
                                                char **transcript);

int32_t rust_asr_transcriber_transcribe_bytes(RustAsrTranscriber *transcriber,
                                                 const unsigned char *audio_bytes,
                                                 uintptr_t audio_bytes_len,
                                                 const char *format_hint,
                                                 char **transcript);

char *rust_asr_last_error_message();

void rust_asr_string_free(char *value);

}  // extern "C"

}  // namespace rust_asr

#endif  // RUST_ASR_HPP
