#ifndef W2V_BERT_UK_HPP
#define W2V_BERT_UK_HPP

/* Generated by cbindgen. Do not edit manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace w2v_bert_uk {

constexpr static const int32_t W2V_BERT_UK_OK = 0;

constexpr static const int32_t W2V_BERT_UK_ERROR = -1;

struct W2vBertUkOptions {
  const char *model;
  const char *tokenizer;
  const char *lm;
  const char *ort_dylib_path;
  const char *ort_optimization;
  const char *w2v_model_source;
  uint32_t beam_width;
  float lm_weight;
  float word_bonus;
  uint32_t fallback_sample_rate;
  uint32_t w2v_sample_rate;
  uint32_t w2v_feature_size;
  uint32_t w2v_stride;
  uint32_t w2v_feature_dim;
  float w2v_padding_value;
  uint32_t blank_id;
  uint32_t n_best;
  int32_t log_language_model;
  int32_t log_accelerator;
  int32_t skip_decode_errors;
  int32_t normalize_spaces;
  int32_t drop_empty_candidates;
  int32_t lm_bos;
  int32_t lm_eos;
};

struct W2vBertUkTranscriber {
  uint8_t _private[0];
};

extern "C" {

W2vBertUkOptions w2v_bert_uk_options_default();

int32_t w2v_bert_uk_initialize_ort(const char *ort_dylib_path, bool *initialized);

int32_t w2v_bert_uk_preload_cuda_dylibs(const char *cuda_lib_dir, const char *cudnn_lib_dir);

int32_t w2v_bert_uk_transcribe_file(const char *audio_file,
                                    const W2vBertUkOptions *options,
                                    char **transcript);

int32_t w2v_bert_uk_transcribe_bytes(const unsigned char *audio_bytes,
                                     uintptr_t audio_bytes_len,
                                     const char *format_hint,
                                     const W2vBertUkOptions *options,
                                     char **transcript);

int32_t w2v_bert_uk_transcriber_new(const W2vBertUkOptions *options,
                                    W2vBertUkTranscriber **transcriber);

void w2v_bert_uk_transcriber_free(W2vBertUkTranscriber *transcriber);

int32_t w2v_bert_uk_transcriber_transcribe_file(W2vBertUkTranscriber *transcriber,
                                                const char *audio_file,
                                                char **transcript);

int32_t w2v_bert_uk_transcriber_transcribe_bytes(W2vBertUkTranscriber *transcriber,
                                                 const unsigned char *audio_bytes,
                                                 uintptr_t audio_bytes_len,
                                                 const char *format_hint,
                                                 char **transcript);

char *w2v_bert_uk_last_error_message();

void w2v_bert_uk_string_free(char *value);

}  // extern "C"

}  // namespace w2v_bert_uk

#endif  // W2V_BERT_UK_HPP
